/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CanvasFrameRouteImport } from './routes/canvas-frame'
import { Route as SplatRouteImport } from './routes/$'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as CanvasEditorIndexRouteImport } from './routes/canvas-editor/index'
import { Route as EditorSplatRouteImport } from './routes/editor/$'
import { Route as CanvasEditorSplatRouteImport } from './routes/canvas-editor/$'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiAssetsRouteImport } from './routes/api/assets'
import { Route as ApiPagesListRouteImport } from './routes/api/pages/list'
import { Route as ApiAssetsSplatRouteImport } from './routes/api/assets/$'
import { Route as ApiPagesSaveSplatRouteImport } from './routes/api/pages/save/$'
import { Route as ApiPagesRenameSplatRouteImport } from './routes/api/pages/rename/$'
import { Route as ApiPagesLoadSplatRouteImport } from './routes/api/pages/load/$'
import { Route as ApiPagesDeleteSplatRouteImport } from './routes/api/pages/delete/$'
import { Route as ApiPagesCreateFolderSplatRouteImport } from './routes/api/pages/create-folder/$'

const CanvasFrameRoute = CanvasFrameRouteImport.update({
  id: '/canvas-frame',
  path: '/canvas-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasEditorIndexRoute = CanvasEditorIndexRouteImport.update({
  id: '/canvas-editor/',
  path: '/canvas-editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorSplatRoute = EditorSplatRouteImport.update({
  id: '/editor/$',
  path: '/editor/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasEditorSplatRoute = CanvasEditorSplatRouteImport.update({
  id: '/canvas-editor/$',
  path: '/canvas-editor/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsRoute = ApiAssetsRouteImport.update({
  id: '/api/assets',
  path: '/api/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesListRoute = ApiPagesListRouteImport.update({
  id: '/api/pages/list',
  path: '/api/pages/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsSplatRoute = ApiAssetsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAssetsRoute,
} as any)
const ApiPagesSaveSplatRoute = ApiPagesSaveSplatRouteImport.update({
  id: '/api/pages/save/$',
  path: '/api/pages/save/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesRenameSplatRoute = ApiPagesRenameSplatRouteImport.update({
  id: '/api/pages/rename/$',
  path: '/api/pages/rename/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesLoadSplatRoute = ApiPagesLoadSplatRouteImport.update({
  id: '/api/pages/load/$',
  path: '/api/pages/load/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesDeleteSplatRoute = ApiPagesDeleteSplatRouteImport.update({
  id: '/api/pages/delete/$',
  path: '/api/pages/delete/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesCreateFolderSplatRoute =
  ApiPagesCreateFolderSplatRouteImport.update({
    id: '/api/pages/create-folder/$',
    path: '/api/pages/create-folder/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/canvas-frame': typeof CanvasFrameRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/canvas-editor/$': typeof CanvasEditorSplatRoute
  '/editor/$': typeof EditorSplatRoute
  '/canvas-editor/': typeof CanvasEditorIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/pages/list': typeof ApiPagesListRoute
  '/api/pages/create-folder/$': typeof ApiPagesCreateFolderSplatRoute
  '/api/pages/delete/$': typeof ApiPagesDeleteSplatRoute
  '/api/pages/load/$': typeof ApiPagesLoadSplatRoute
  '/api/pages/rename/$': typeof ApiPagesRenameSplatRoute
  '/api/pages/save/$': typeof ApiPagesSaveSplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/canvas-frame': typeof CanvasFrameRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/canvas-editor/$': typeof CanvasEditorSplatRoute
  '/editor/$': typeof EditorSplatRoute
  '/canvas-editor': typeof CanvasEditorIndexRoute
  '/editor': typeof EditorIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/pages/list': typeof ApiPagesListRoute
  '/api/pages/create-folder/$': typeof ApiPagesCreateFolderSplatRoute
  '/api/pages/delete/$': typeof ApiPagesDeleteSplatRoute
  '/api/pages/load/$': typeof ApiPagesLoadSplatRoute
  '/api/pages/rename/$': typeof ApiPagesRenameSplatRoute
  '/api/pages/save/$': typeof ApiPagesSaveSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/canvas-frame': typeof CanvasFrameRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/canvas-editor/$': typeof CanvasEditorSplatRoute
  '/editor/$': typeof EditorSplatRoute
  '/canvas-editor/': typeof CanvasEditorIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/pages/list': typeof ApiPagesListRoute
  '/api/pages/create-folder/$': typeof ApiPagesCreateFolderSplatRoute
  '/api/pages/delete/$': typeof ApiPagesDeleteSplatRoute
  '/api/pages/load/$': typeof ApiPagesLoadSplatRoute
  '/api/pages/rename/$': typeof ApiPagesRenameSplatRoute
  '/api/pages/save/$': typeof ApiPagesSaveSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/canvas-frame'
    | '/api/assets'
    | '/api/export'
    | '/canvas-editor/$'
    | '/editor/$'
    | '/canvas-editor/'
    | '/editor/'
    | '/api/assets/$'
    | '/api/pages/list'
    | '/api/pages/create-folder/$'
    | '/api/pages/delete/$'
    | '/api/pages/load/$'
    | '/api/pages/rename/$'
    | '/api/pages/save/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/canvas-frame'
    | '/api/assets'
    | '/api/export'
    | '/canvas-editor/$'
    | '/editor/$'
    | '/canvas-editor'
    | '/editor'
    | '/api/assets/$'
    | '/api/pages/list'
    | '/api/pages/create-folder/$'
    | '/api/pages/delete/$'
    | '/api/pages/load/$'
    | '/api/pages/rename/$'
    | '/api/pages/save/$'
  id:
    | '__root__'
    | '/$'
    | '/canvas-frame'
    | '/api/assets'
    | '/api/export'
    | '/canvas-editor/$'
    | '/editor/$'
    | '/canvas-editor/'
    | '/editor/'
    | '/api/assets/$'
    | '/api/pages/list'
    | '/api/pages/create-folder/$'
    | '/api/pages/delete/$'
    | '/api/pages/load/$'
    | '/api/pages/rename/$'
    | '/api/pages/save/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  CanvasFrameRoute: typeof CanvasFrameRoute
  ApiAssetsRoute: typeof ApiAssetsRouteWithChildren
  ApiExportRoute: typeof ApiExportRoute
  CanvasEditorSplatRoute: typeof CanvasEditorSplatRoute
  EditorSplatRoute: typeof EditorSplatRoute
  CanvasEditorIndexRoute: typeof CanvasEditorIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
  ApiPagesListRoute: typeof ApiPagesListRoute
  ApiPagesCreateFolderSplatRoute: typeof ApiPagesCreateFolderSplatRoute
  ApiPagesDeleteSplatRoute: typeof ApiPagesDeleteSplatRoute
  ApiPagesLoadSplatRoute: typeof ApiPagesLoadSplatRoute
  ApiPagesRenameSplatRoute: typeof ApiPagesRenameSplatRoute
  ApiPagesSaveSplatRoute: typeof ApiPagesSaveSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/canvas-frame': {
      id: '/canvas-frame'
      path: '/canvas-frame'
      fullPath: '/canvas-frame'
      preLoaderRoute: typeof CanvasFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-editor/': {
      id: '/canvas-editor/'
      path: '/canvas-editor'
      fullPath: '/canvas-editor/'
      preLoaderRoute: typeof CanvasEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$': {
      id: '/editor/$'
      path: '/editor/$'
      fullPath: '/editor/$'
      preLoaderRoute: typeof EditorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-editor/$': {
      id: '/canvas-editor/$'
      path: '/canvas-editor/$'
      fullPath: '/canvas-editor/$'
      preLoaderRoute: typeof CanvasEditorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets': {
      id: '/api/assets'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/list': {
      id: '/api/pages/list'
      path: '/api/pages/list'
      fullPath: '/api/pages/list'
      preLoaderRoute: typeof ApiPagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$': {
      id: '/api/assets/$'
      path: '/$'
      fullPath: '/api/assets/$'
      preLoaderRoute: typeof ApiAssetsSplatRouteImport
      parentRoute: typeof ApiAssetsRoute
    }
    '/api/pages/save/$': {
      id: '/api/pages/save/$'
      path: '/api/pages/save/$'
      fullPath: '/api/pages/save/$'
      preLoaderRoute: typeof ApiPagesSaveSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/rename/$': {
      id: '/api/pages/rename/$'
      path: '/api/pages/rename/$'
      fullPath: '/api/pages/rename/$'
      preLoaderRoute: typeof ApiPagesRenameSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/load/$': {
      id: '/api/pages/load/$'
      path: '/api/pages/load/$'
      fullPath: '/api/pages/load/$'
      preLoaderRoute: typeof ApiPagesLoadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/delete/$': {
      id: '/api/pages/delete/$'
      path: '/api/pages/delete/$'
      fullPath: '/api/pages/delete/$'
      preLoaderRoute: typeof ApiPagesDeleteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/create-folder/$': {
      id: '/api/pages/create-folder/$'
      path: '/api/pages/create-folder/$'
      fullPath: '/api/pages/create-folder/$'
      preLoaderRoute: typeof ApiPagesCreateFolderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAssetsRouteChildren {
  ApiAssetsSplatRoute: typeof ApiAssetsSplatRoute
}

const ApiAssetsRouteChildren: ApiAssetsRouteChildren = {
  ApiAssetsSplatRoute: ApiAssetsSplatRoute,
}

const ApiAssetsRouteWithChildren = ApiAssetsRoute._addFileChildren(
  ApiAssetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  CanvasFrameRoute: CanvasFrameRoute,
  ApiAssetsRoute: ApiAssetsRouteWithChildren,
  ApiExportRoute: ApiExportRoute,
  CanvasEditorSplatRoute: CanvasEditorSplatRoute,
  EditorSplatRoute: EditorSplatRoute,
  CanvasEditorIndexRoute: CanvasEditorIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
  ApiPagesListRoute: ApiPagesListRoute,
  ApiPagesCreateFolderSplatRoute: ApiPagesCreateFolderSplatRoute,
  ApiPagesDeleteSplatRoute: ApiPagesDeleteSplatRoute,
  ApiPagesLoadSplatRoute: ApiPagesLoadSplatRoute,
  ApiPagesRenameSplatRoute: ApiPagesRenameSplatRoute,
  ApiPagesSaveSplatRoute: ApiPagesSaveSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
